// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySite.Infrastructure.Postgres.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MySite.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(MySiteDbContext))]
    [Migration("20261006231005_ContentSchema")]
    partial class ContentSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MySite.Domain.Content.OwnerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_owner_profiles");

                    b.ToTable("owner_profiles", (string)null);
                });

            modelBuilder.Entity("MySite.Domain.Content.OwnerProfileTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("about");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("headline");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("locale");

                    b.Property<Guid>("OwnerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_profile_id");

                    b.HasKey("Id")
                        .HasName("pk_owner_profile_translations");

                    b.HasIndex("OwnerProfileId", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_owner_profile_translations_owner_profile_id_locale");

                    b.ToTable("owner_profile_translations", (string)null);
                });

            modelBuilder.Entity("MySite.Domain.Content.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("link");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("ix_projects_is_published");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_projects_sort_order");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("MySite.Domain.Content.ProjectStackItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_project_stack_items");

                    b.HasIndex("ProjectId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_project_stack_items_project_id_position");

                    b.ToTable("project_stack_items", (string)null);
                });

            modelBuilder.Entity("MySite.Domain.Content.ProjectTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("locale");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_project_translations");

                    b.HasIndex("ProjectId", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_project_translations_project_id_locale");

                    b.ToTable("project_translations", (string)null);
                });

            modelBuilder.Entity("MySite.Domain.Content.OwnerProfileTranslation", b =>
                {
                    b.HasOne("MySite.Domain.Content.OwnerProfile", null)
                        .WithMany("Translations")
                        .HasForeignKey("OwnerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_owner_profile_translations_owner_profiles_owner_profile_id");
                });

            modelBuilder.Entity("MySite.Domain.Content.ProjectStackItem", b =>
                {
                    b.HasOne("MySite.Domain.Content.Project", null)
                        .WithMany("Stack")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_stack_items_projects_project_id");
                });

            modelBuilder.Entity("MySite.Domain.Content.ProjectTranslation", b =>
                {
                    b.HasOne("MySite.Domain.Content.Project", null)
                        .WithMany("Translations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_translations_projects_project_id");
                });

            modelBuilder.Entity("MySite.Domain.Content.OwnerProfile", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("MySite.Domain.Content.Project", b =>
                {
                    b.Navigation("Stack");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
